### ISSUE TITLE
did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'

### ISSUE THREAD

**Issue by lukaszachy** [psss/did#385]
Filled as RHBZ https://bugzilla.redhat.com/show_bug.cgi?id=2328006
'FancyURLopener' is deprecated since 3.3 and removed in 3.14 - https://docs.python.org/3/library/urllib.request.html#urllib.request.FancyURLopener

It is used only in gerrit plugin.
Python3.14 is planned in Fedora 43 so if we want to have did there we need to fix it.

**Comment by sandrobonazzola** [comment]
duplicate of #298

**Comment by sandrobonazzola** [comment]
Fixed via #390
